### ISSUE TITLE
題目中有「～」符號

### ISSUE THREAD

**Issue by msglight4874** [wangchou/Shadowing#24]
「～」這個符號照著唸好像沒辦法辨認出來，不知道是我發音問題還是題目問題，再麻煩大大解惑了，謝謝。

![27edd62e-78b6-4d95-94af-5695f3b5da6a](https://user-images.githubusercontent.com/11512544/52522660-49358580-2cc3-11e9-943c-0a3000b89920.jpeg)

**Comment by wangchou** [comment]
抱歉沒想到有人會從這發 issue, 現在才看到。 謝謝回報〜

**這個 bug 會在下一版一起修正。** 
(這週末會上架 1.2 小改版)

自動 TTS -> Siri 自動檢測時，好像唸成「いいな」。
因為算分會去除標點符號。所以就檢測過了。
剛剛測唸「な短音」反而會１００分。。。XD
![img_8360](https://user-images.githubusercontent.com/32716/53467744-77241380-3a92-11e9-8004-55fc07e9b3d2.png)

**Comment by wangchou** [comment]
fixed in #25
